# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: about
    url: '#about'
    weight: 10
  - name: blog
    url: 'https://linkedin.com/in/gkthiruvathukal'
    weight: 20
  - name: contact
    url: '#contact'
    weight: 30
  - name: publications
    url: '#publications'
    weight: 40
  - name: research
    url: '#research'
    weight: 50
  - name: teaching
    url: '#teaching'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
